update 1

diff --git a/dpkg/info/apparmor.postinst b/dpkg/info/apparmor.postinst
--- a/dpkg/info/apparmor.postinst
+++ b/dpkg/info/apparmor.postinst
@@ -89,17 +89,6 @@ EOM
             mv -n "$tmp" /etc/apparmor.d/tunables/xdg-user-dirs.d/site.local
             chmod 644 /etc/apparmor.d/tunables/xdg-user-dirs.d/site.local
         fi
-
-        # Remove various profiles from Ubuntu Touch since they no longer exist
-        # in the archive and require files from apparmor-easyprof-ubuntu (which
-        # was also removed) to load correctly.
-	if dpkg --compare-versions "$2" lt-nl "2.12-4ubuntu4"; then
-            for i in usr.bin.media-hub-server usr.bin.mediascanner-service-2.0 usr.lib.mediascanner-2.0.mediascanner-extractor usr.bin.messaging-app usr.bin.webbrowser-app ; do
-                rm -f "/etc/apparmor.d/$i"
-                rm -f "/etc/apparmor.d/cache/$i"
-                rm -f "/etc/apparmor.d/local/$i"
-            done
-        fi
         ;;
 
     abort-upgrade)
@@ -115,33 +104,21 @@ esac
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
 
-# Automatically added by dh_systemd_enable/11.1.6ubuntu1
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
-	# This will only remove masks created by d-s-h on package removal.
-	deb-systemd-helper unmask 'apparmor.service' >/dev/null || true
-
-	# was-enabled defaults to true, so new installations run enable.
-	if deb-systemd-helper --quiet was-enabled 'apparmor.service'; then
-		# Enables the unit on first installation, creates new
-		# symlinks on upgrades if the unit file has changed.
-		deb-systemd-helper enable 'apparmor.service' >/dev/null || true
-	else
-		# Update the statefile to add new symlinks (if any), which need to be
-		# cleaned up on purge. Also remove old symlinks.
-		deb-systemd-helper update-state 'apparmor.service' >/dev/null || true
-	fi
-fi
-# End automatically added section
-# Automatically added by dh_installdeb/11.1.6ubuntu1
-dpkg-maintscript-helper rm_conffile /etc/apparmor.d/abstractions/ubuntu-sdk-base 2.8.0-0ubuntu20\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/init/apparmor.conf 2.11.0-11\~ -- "$@"
-# End automatically added section
-# Automatically added by dh_installinit/11.1.6ubuntu1
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+# Automatically added by dh_installinit
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
 	if [ -x "/etc/init.d/apparmor" ]; then
-		update-rc.d apparmor defaults >/dev/null || true
+		update-rc.d apparmor start 37 S . >/dev/null || true
 	fi
 fi
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/apparmor/functions 2.5.1-0ubuntu4 -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/apparmor/rc.apparmor.functions 2.5.1-0ubuntu4 -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/apparmor.d/abstractions/ubuntu-sdk-base 2.8.0-0ubuntu20~ -- "$@"
 # End automatically added section
 
 
@@ -153,6 +130,13 @@ case "$1" in
             clear_cache || true
             load_configured_profiles || true
         fi
+
+        # Discard the return code and just make sure the md5sums are updated
+        # so on next boot the upstart/initscript will have updated md5sums and
+        # won't clear out the cache. This does not affect system-image updates
+        # since /etc/system-image/writable-paths is configured to prefer the
+        # files on the device (and the apparmor upstart job handles this).
+        compare_and_save_debsums apparmor || true
         ;;
 esac
 
diff --git a/dpkg/info/mtr-tiny.postinst b/dpkg/info/mtr-tiny.postinst
--- a/dpkg/info/mtr-tiny.postinst
+++ b/dpkg/info/mtr-tiny.postinst
@@ -3,17 +3,17 @@
 set -e
 
 if [ "$1" = configure ]; then
-    # If setcap is installed, try setting cap_net_raw+ep,
+    # If we have setcap is installed, try setting cap_net_raw+ep,
     # which allows us to install our binaries without the setuid
     # bit.
     if command -v setcap > /dev/null; then
-        if ! setcap cap_net_raw+ep /usr/bin/mtr-packet; then
-            echo "Setcap failed on /usr/bin/mtr-packet, falling back to setuid" >&2
-            chmod u+s /usr/bin/mtr-packet
+        if ! setcap cap_net_raw+ep /usr/bin/mtr; then
+            echo "Setcap failed on /usr/bin/mtr, falling back to setuid" >&2
+            chmod u+s /usr/bin/mtr
         fi
     else
         echo "Setcap is not installed, falling back to setuid" >&2
-        chmod u+s /usr/bin/mtr-packet
+        chmod u+s /usr/bin/mtr
     fi
 fi
 
diff --git a/dpkg/info/rsyslog.postinst b/dpkg/info/rsyslog.postinst
--- a/dpkg/info/rsyslog.postinst
+++ b/dpkg/info/rsyslog.postinst
@@ -16,6 +16,7 @@ set -e
 
 case "$1" in
     configure)
+
 	user_conf=/etc/rsyslog.d/50-default.conf
 	default_conf=/usr/share/rsyslog/50-default.conf
 
@@ -25,27 +26,26 @@ case "$1" in
 	adduser --system --group --no-create-home --quiet syslog || true
 	adduser syslog adm || true
 
-	if which systemd-tmpfiles >/dev/null
-	then
-	    systemd-tmpfiles --create /usr/lib/tmpfiles.d/00rsyslog.conf
-	else
-	    # fix ownership of work directory (LP: #1075901)
-            chown syslog:adm /var/spool/rsyslog
+	# fix ownership of work directory (LP: #1075901)
+        chown syslog:adm /var/spool/rsyslog
 
-	    # ensure that rsyslogd can create log files after dropping
-	    # privileges
-	    chgrp syslog /var/log
-	    chmod g+w /var/log
+	# ensure that rsyslogd can create log files after dropping
+	# privileges
+	chgrp syslog /var/log
+	chmod g+w /var/log
 
-	    # Fix permissions of the spool/work directory (Bug: #693099)
-	    chmod 700 /var/spool/rsyslog
+	# /run transition (Bug: #633036)
+	if dpkg --compare-versions "$2" lt "5.8.2-2"; then
+		rm -f /lib/init/rw/sendsigs.omit.d/rsyslog
 	fi
-    ;;
 
-    triggered)
-	# Try to restart rsyslog
-	invoke-rc.d rsyslog try-restart || true
-	exit 0
+	# Fix permissions of the spool/work directory (Bug: #693099)
+	chmod 700 /var/spool/rsyslog
+
+	# Clean up temporary syslog.service symlink
+	if [ -d /run/systemd/system ] &&  dpkg --compare-versions "$2" lt-nl "7.4.1-2" ; then
+		rm -f /run/systemd/system/syslog.service
+	fi
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
@@ -57,37 +57,22 @@ case "$1" in
     ;;
 esac
 
-# Automatically added by dh_systemd_enable/11.1.6ubuntu1
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
-	# This will only remove masks created by d-s-h on package removal.
-	deb-systemd-helper unmask 'rsyslog.service' >/dev/null || true
+# Automatically added by dh_systemd_enable
+# This will only remove masks created by d-s-h on package removal.
+deb-systemd-helper unmask rsyslog.service >/dev/null || true
 
-	# was-enabled defaults to true, so new installations run enable.
-	if deb-systemd-helper --quiet was-enabled 'rsyslog.service'; then
-		# Enables the unit on first installation, creates new
-		# symlinks on upgrades if the unit file has changed.
-		deb-systemd-helper enable 'rsyslog.service' >/dev/null || true
-	else
-		# Update the statefile to add new symlinks (if any), which need to be
-		# cleaned up on purge. Also remove old symlinks.
-		deb-systemd-helper update-state 'rsyslog.service' >/dev/null || true
-	fi
+# was-enabled defaults to true, so new installations run enable.
+if deb-systemd-helper --quiet was-enabled rsyslog.service; then
+	# Enables the unit on first installation, creates new
+	# symlinks on upgrades if the unit file has changed.
+	deb-systemd-helper enable rsyslog.service >/dev/null || true
+else
+	# Update the statefile to add new symlinks (if any), which need to be
+	# cleaned up on purge. Also remove old symlinks.
+	deb-systemd-helper update-state rsyslog.service >/dev/null || true
 fi
 # End automatically added section
-# Automatically added by dh_apparmor/2.12-4ubuntu5
-aa_is_enabled() {
-   if command aa-enabled >/dev/null 2>&1; then
-      # apparmor >= 2.10.95-2
-      aa-enabled --quiet 2>/dev/null
-   else
-      # apparmor << 2.10.95-2
-      # (This should be removed once Debian Stretch and Ubuntu 18.04 are out.)
-      rc=0
-      aa-status --enabled 2>/dev/null || rc=$?
-      [ "$rc" = 0 ] || [ "$rc" = 2 ]
-   fi
-}
-
+# Automatically added by dh_apparmor
 if [ "$1" = "configure" ]; then
     APP_PROFILE="/etc/apparmor.d/usr.sbin.rsyslogd"
     if [ -f "$APP_PROFILE" ]; then
@@ -95,19 +80,25 @@ if [ "$1" = "configure" ]; then
         LOCAL_APP_PROFILE="/etc/apparmor.d/local/usr.sbin.rsyslogd"
 
         test -e "$LOCAL_APP_PROFILE" || {
-            mkdir -p `dirname "$LOCAL_APP_PROFILE"`
-            install --mode 644 /dev/null "$LOCAL_APP_PROFILE"
+            tmp=`mktemp`
+        cat <<EOM > "$tmp"
+# Site-specific additions and overrides for usr.sbin.rsyslogd.
+# For more details, please see /etc/apparmor.d/local/README.
+EOM
+            mkdir `dirname "$LOCAL_APP_PROFILE"` 2>/dev/null || true
+            mv -f "$tmp" "$LOCAL_APP_PROFILE"
+            chmod 644 "$LOCAL_APP_PROFILE"
         }
 
         # Reload the profile, including any abstraction updates
-        if aa_is_enabled; then
+        if aa-status --enabled 2>/dev/null; then
             apparmor_parser -r -T -W "$APP_PROFILE" || true
         fi
     fi
 fi
 # End automatically added section
-# Automatically added by dh_installinit/11.1.6ubuntu1
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+# Automatically added by dh_installinit
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
 	# In case this system is running systemd, we need to ensure that all
 	# necessary tmpfiles (if any) are created before starting.
 	if [ -d /run/systemd/system ] ; then
@@ -115,19 +106,18 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installdeb/11.1.6ubuntu1
-dpkg-maintscript-helper rm_conffile /etc/init/rsyslog.conf 8.16.0-1ubuntu9\~ rsyslog -- "$@"
-# End automatically added section
-# Automatically added by dh_installinit/11.1.6ubuntu1
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+# Automatically added by dh_installinit
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
 	if [ -x "/etc/init.d/rsyslog" ]; then
 		update-rc.d rsyslog defaults >/dev/null
+	fi
+	if [ -x "/etc/init.d/rsyslog" ] || [ -e "/etc/init/rsyslog.conf" ]; then
 		if [ -n "$2" ]; then
 			_dh_action=restart
 		else
 			_dh_action=start
 		fi
-		invoke-rc.d rsyslog $_dh_action || exit 1
+		invoke-rc.d rsyslog $_dh_action || exit $?
 	fi
 fi
 # End automatically added section
diff --git a/dpkg/info/systemd.postinst b/dpkg/info/systemd.postinst
--- a/dpkg/info/systemd.postinst
+++ b/dpkg/info/systemd.postinst
@@ -28,8 +28,10 @@ if [ "$1" = "triggered" ]; then
     exit 0
 fi
 
-# Enable getty and remote-fs.target by default on new installs
-if [ -z "$2" ]; then
+# Enable getty and remote-fs.target by default on new installs, and on
+# upgrades from old systemd versions (where the symlinks included as deb
+# content, and will thus have been removed by dpkg during the upgrade).
+if dpkg --compare-versions "$2" lt "214-1"; then
     systemctl enable getty@tty1.service || true
     systemctl enable remote-fs.target || true
 fi
@@ -39,39 +41,8 @@ if dpkg --compare-versions "$2" lt "218-11~"; then
     systemctl enable systemd-timesyncd.service || true
 fi
 
-# Enable resolved by default on new installs installs and upgrades
-if dpkg --compare-versions "$2" lt "234-1ubuntu2~"; then
-    systemctl enable systemd-resolved.service || true
-fi
-
-# Drop stock /etc/rc.local on upgrades
-if dpkg --compare-versions "$2" lt "234-2ubuntu11~"; then
-        if [ -f /etc/rc.local ]; then
-                if [ "10fd9f051accb6fd1f753f2d48371890" = "$(md5sum /etc/rc.local | cut -d\  -f1)" ]; then
-                        echo Removing empty /etc/rc.local
-                        rm -f /etc/rc.local || true
-                fi
-        fi
-fi
-
-# Use stub resolve.conf by default on new installs
-if [ -z "$2" ]; then
-    mkdir -p /run/systemd/resolve
-    if [ -e /etc/resolv.conf ]; then
-            cp /etc/resolv.conf /run/systemd/resolve/stub-resolv.conf
-    fi
-    # If /etc/resolv.conf is a bind-mount, moving or replacing
-    # /etc/resolv.conf may fail
-    ln -snf ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf || true
-fi
-
-# Enable ondemand by default on new installs installs and upgrades
-if [ -e /lib/systemd/system/ondemand.service ] && dpkg --compare-versions "$2" lt "231-7~"; then
-    systemctl enable ondemand.service || true
-fi
-
 # Do a one-time migration of the local time setting
-if [ -z "$2" ]; then
+if dpkg --compare-versions "$2" lt "228-5ubuntu3"; then
     if [ -f /etc/default/rcS ]; then
         . /etc/default/rcS
     fi
@@ -81,7 +52,13 @@ if [ -z "$2" ]; then
 fi
 
 # Do a one-time migration of the TMPTIME setting
-if [ -z "$2" ]; then
+if dpkg --compare-versions "$2" lt "204-9"; then
+    # Fix up potentially broken tmp.conf, see Debian#738862
+    if [ -e /etc/tmpfiles.d/tmp.conf ]; then
+        sed -i '/^# Clear \/var\/tmp/d' /etc/tmpfiles.d/tmp.conf
+        sed -i 's,^\(d /var/tmp\),#\1,g' /etc/tmpfiles.d/tmp.conf
+    fi
+
     if [ -f /etc/default/rcS ]; then
         . /etc/default/rcS
     fi
@@ -100,7 +77,7 @@ EOF
 fi
 
 # Do a one-time migration of the RAMTMP setting
-if [ -z "$2" ]; then
+if dpkg --compare-versions "$2" lt "204-8"; then
     if [ -f /etc/default/rcS ]; then
         . /etc/default/rcS
     fi
@@ -120,41 +97,47 @@ fi
 systemd-machine-id-setup
 
 # Setup system users and groups
-addgroup --quiet --system systemd-journal
+addgroup --system systemd-journal
 
-# Enable persistent journal, in auto-mode, by default on new installs installs and upgrades
-if dpkg --compare-versions "$2" lt "235-3ubuntu3~"; then
-    mkdir -p /var/log/journal
-    # create tmpfiles only when running systemd, otherwise %b substitution fails
-    if [ -d /run/systemd/system ]; then
-        systemd-tmpfiles --create --prefix /var/log/journal
-    fi
-fi
-
+adduser --quiet --system --group --no-create-home --home /run/systemd \
+    --gecos "systemd Time Synchronization" systemd-timesync
 adduser --quiet --system --group --no-create-home --home /run/systemd/netif \
     --gecos "systemd Network Management" systemd-network
 adduser --quiet --system --group --no-create-home --home /run/systemd/resolve \
     --gecos "systemd Resolver" systemd-resolve
+adduser --quiet --system --group --no-create-home --home /run/systemd \
+    --gecos "systemd Bus Proxy" systemd-bus-proxy
 
 # Initial update of the Message Catalogs database
 _update_catalog
 
-# Disable networkd when upgrading from broken versions 8..10. Turns out
-# enabling networkd unconditionally has long boot time side-effects
-if dpkg --compare-versions "$2" gt "234-2ubuntu8~" &&
-   dpkg --compare-versions "$2" lt "234-2ubuntu11~"; then
-    systemctl disable systemd-networkd-wait-online.service || true
+# Make systemd-detect-virt utility usable for non-root users
+setcap cap_dac_override,cap_sys_ptrace=ep /usr/bin/systemd-detect-virt || true
+
+# Re-run systemctl enable for any service that was enabled when preinst was run.
+if dpkg --compare-versions "$2" ge "204" && [ -e /run/systemd/was-enabled ]; then
+    while read UNIT ; do
+        # 220-6 stopped shipping tmp.mount, transition it on machines which had
+        # it enabled
+        if [ "$UNIT" = tmp.mount ] && dpkg --compare-versions "$2" lt-nl "220-6~"; then
+            if [ ! -e /etc/systemd/system/tmp.mount ]; then
+                echo "moving enabled tmp.mount to /etc/systemd/system/..."
+                cp /usr/share/systemd/tmp.mount /etc/systemd/system/tmp.mount
+                # clean up the symlink, to have it re-created below
+                systemctl disable $UNIT
+            fi
+        fi
+        systemctl enable $UNIT || true
+    done </run/systemd/was-enabled || true
 fi
 
-# skip daemon-reexec and try-restarts during shutdown to avoid hitting LP: #1803391
-if [ -n "$2" ] && [ "$(systemctl is-system-running)" != "stopping" ]; then
+if [ -n "$2" ]; then
     _systemctl daemon-reexec || true
     # don't restart logind; this can be done again once this gets implemented:
     # https://github.com/systemd/systemd/issues/1163
     _systemctl try-restart systemd-networkd.service || true
     _systemctl try-restart systemd-resolved.service || true
     _systemctl try-restart systemd-timesyncd.service || true
-    _systemctl try-restart systemd-journald.service || true
 fi
 
 # Cleanup hwclock-save.service, which was shipped in jessie.
@@ -165,34 +148,52 @@ if dpkg --compare-versions "$2" lt-nl "228-5~"; then
    done
 fi
 
-if dpkg --compare-versions "$2" lt-nl "235-3~"; then
-    # systemd-bus-proxyd got dropped before stretch, and never created any file
-    deluser --system systemd-bus-proxy || true
+# start systemd-networkd-resolvconf-update.path on first install/upgrade if
+# required
+if _systemctl is-active --quiet resolvconf; then
+    _systemctl start systemd-networkd-resolvconf-update.path || true
 fi
 
-if dpkg --compare-versions "$2" lt-nl "236-1~"; then
-    # Clean up old /var/lib/systemd/clock on upgrade.
-    # The clock file used by systemd-timesyncd is now stored in
-    # StateDirectory=systemd/timesync.
-    rm -f /var/lib/systemd/clock
+# migrate mountall specific fstab options to standard util-linux "nofail" option
+if dpkg --compare-versions "$2" lt "221-1" && [ -w /etc/fstab ]; then
+    if awk '{ gsub(/^nobootwait/, "nofail", $4); gsub(/,nobootwait/, ",nofail", $4); gsub(/^optional/, "nofail", $4); gsub(/,optional/, ",nofail", $4); print }' /etc/fstab > /etc/fstab.new; then
+        if cmp --quiet /etc/fstab /etc/fstab.new; then
+            rm /etc/fstab.new  # nothing to migrate
+        else
+            echo "Replacing obsolete mountall options in /etc/fstab... (backup in /etc/fstab.mountall)"
+            mv /etc/fstab /etc/fstab.mountall
+            mv /etc/fstab.new /etc/fstab
+        fi
+    else
+        echo "WARNING! Could not create /etc/fstab.new for migrating obsolete mountall options" >&2
+    fi
 fi
 
-# Process all tmpfiles that we ship, including any overrides in
-# runtime-dir/sysadmin-dir/other packages (e.g. rsyslog)
-#
-# Ignore if this fails, because e.g. %b will fail on WSL
-systemd-tmpfiles --create || :
-
-# Automatically added by dh_installdeb/11.1.6ubuntu1
-dpkg-maintscript-helper rm_conffile /etc/X11/xinit/xinitrc.d/50-systemd-user.sh 228-3\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/systemd/bootchart.conf 230-1\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.hostname1.conf 233-3\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.locale1.conf 233-3\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.login1.conf 233-3\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.machine1.conf 228-5\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.network1.conf 233-3\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.resolve1.conf 233-3\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.systemd1.conf 233-3\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.timedate1.conf 233-3\~ -- "$@"
+# Automatically added by dh_installinit
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
+	# In case this system is running systemd, we need to ensure that all
+	# necessary tmpfiles (if any) are created before starting.
+	if [ -d /run/systemd/system ] ; then
+		systemd-tmpfiles --create /usr/lib/tmpfiles.d/debian.conf /usr/lib/tmpfiles.d/home.conf /usr/lib/tmpfiles.d/journal-nocow.conf /usr/lib/tmpfiles.d/legacy.conf /usr/lib/tmpfiles.d/systemd-nologin.conf /usr/lib/tmpfiles.d/systemd.conf /usr/lib/tmpfiles.d/tmp.conf /usr/lib/tmpfiles.d/var.conf /usr/lib/tmpfiles.d/x11.conf >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/systemctl-bash-completion.sh 204-1~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/systemd-bash-completion.sh 204-1~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper mv_conffile /etc/systemd/systemd-logind.conf /etc/systemd/logind.conf 204-1~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper mv_conffile /etc/systemd/systemd-journald.conf /etc/systemd/journald.conf 204-1~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.machine1.conf 228-5~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/X11/xinit/xinitrc.d/50-systemd-user.sh 228-3~ -- "$@"
 # End automatically added section
 
diff --git a/dpkg/info/udev.postinst b/dpkg/info/udev.postinst
--- a/dpkg/info/udev.postinst
+++ b/dpkg/info/udev.postinst
@@ -42,6 +42,11 @@ update_initramfs() {
 }
 
 upgrade_fixes() {
+  if dpkg --compare-versions "$2" lt "204-1"; then
+    # We dropped udev-mtab with udev 204.
+    update-rc.d udev-mtab remove
+  fi
+
   if dpkg --compare-versions "$2" lt "226-1"; then
     update-rc.d udev-finish remove
   fi
@@ -51,14 +56,12 @@ upgrade_fixes() {
   if dpkg --compare-versions "$2" lt-nl "220-7~" &&
      [ ! -e /etc/udev/rules.d/70-persistent-net.rules ] &&
      [ ! -e /etc/udev/rules.d/80-net-setup-link.rules ] &&
-     [ ! -e /etc/systemd/network/99-default.link ] &&
-     [ ! -L /etc/systemd/network/99-default.link ] &&
-     ! grep -q net.ifnames /proc/cmdline && ! chrooted; then
-    mkdir -p /etc/systemd/network
-    cat <<EOF > /etc/systemd/network/99-default.link
+     ! grep -q net.ifnames /proc/cmdline ; then
+    mkdir -p /etc/udev/rules.d
+    cat <<EOF > /etc/udev/rules.d/80-net-setup-link.rules
 # This machine is most likely a virtualized guest, where the old persistent
 # network interface mechanism (75-persistent-net-generator.rules) did not work.
-# This file disables /lib/systemd/network/99-default.link to avoid
+# This file disables /lib/udev/rules.d/80-net-setup-link.rules to avoid
 # changing network interface names on upgrade. Please read
 # /usr/share/doc/udev/README.Debian.gz about how to migrate to the currently
 # supported mechanism.
@@ -86,17 +89,57 @@ NamePolicy=onboard kernel
 EOF
   fi
 
-  # 232-20 (232-21ubuntu3 in ubuntu) introduced predicable interface names on
-  # s390x for virtio However, we should preserve ethX names on upgrade.
-  if [ -x /usr/share/systemd/write_persistent_net_s390x_virtio ]; then
-      if dpkg --compare-versions "$2" lt-nl "232-21ubuntu3~"; then
-          /usr/share/systemd/write_persistent_net_s390x_virtio || true
-      fi
+  # this is being written under upstart, but not under systemd; clean up
+  # obsolete files
+  if [ -d /run/systemd/system ]; then
+      rm -f /var/log/udev || true
+  fi
+
+  # transition existing interface names on s390x for #1526808
+  if dpkg --compare-versions "$2" lt-nl "228-4ubuntu2" &&
+      [ "$(dpkg --print-architecture)" = "s390x" ]; then
+    sed 's/enccw[0.]*/enc/' -i /etc/network/interfaces /etc/network/interfaces.d/* 2>/dev/null || true
+  fi
+
+  # VMWare BIOS reports implausibly high onboard numbers, this got fixed in
+  # https://github.com/systemd/systemd/commit/6c1e69f9; migrate names in
+  # ifupdown accordingly
+  if dpkg --compare-versions "$2" lt-nl "229-2ubuntu2"; then
+    for i in /sys/class/net/eno*; do
+        if [ "${i#*/eno}" -gt 16383 ] 2>/dev/null; then
+            if slotname=$(udevadm info --query=property $i | grep '^ID_NET_NAME_SLOT='); then
+                slotname=${slotname#*=}
+                echo "Migrating broken onboard-based network interface name ${i##*/} to slot-based name $slotname in /etc/network/interfaces and interfaces.d/..."
+                sed -i "s/\\b${i##*/}\\b/$slotname/g" /etc/network/interfaces /etc/network/interfaces.d/* 2>/dev/null || true
+            else
+                echo "WARNING: Cannot determine proper name for broken onboard-based network interface name ${i##*/}; you must adjust /etc/network/interfaces and interfaces.d/ manually"
+            fi
+        fi
+    done
   fi
 }
 
 update_hwdb() {
   systemd-hwdb --usr update || true
+}
+
+# In udev-204, we ship systemd-udevd.service (upstream name), whereas previous
+# versions used udev.service. We replace udev.service with a symlink to
+# systemd-udevd.service, but systemd (both 44 and 204) exposes weird behavior:
+# After a daemon-reload, it forgets about the /sbin/udevd process in the
+# udev.service cgroup, so a restart will lead to having two udevd processes
+# running — one in the udev.service cgroup and one in the systemd-udevd.service
+# cgroup.
+#
+# To fix this, we explicitly stop udev.service and the corresponding sockets,
+# then issue the daemon-reload, then restart the new systemd-udevd.service (via
+# invoke-rc.d).
+handle_service_rename() {
+  if dpkg --compare-versions "$2" lt "204-1"; then
+    if [ -d /run/systemd/system ]; then
+      systemctl stop udev.service udev-control.socket udev-kernel.socket >/dev/null 2>&1 || true
+    fi
+  fi
 }
 
 case "$1" in
@@ -105,7 +148,7 @@ case "$1" in
     update_hwdb
 
     # Add new system group used by udev rules
-    addgroup --quiet --system input
+    addgroup --system input
 
     if [ -z "$2" ]; then # first install
       if ! chrooted && ! in_debootstrap; then
@@ -115,6 +158,9 @@ case "$1" in
       upgrade_fixes "$@"
       if ! chrooted; then
 	if can_start_udevd; then
+	  handle_service_rename
+	  # This is necessary for the handle_service_rename case, but does not
+	  # hurt in general (invoke-rc.d does it, too).
 	  if [ -d /run/systemd/system ] ; then
 	    systemctl daemon-reload || true
 	  fi
@@ -132,22 +178,36 @@ case "$1" in
     ;;
 esac
 
-# Automatically added by dh_installdeb/11.1.6ubuntu1
-dpkg-maintscript-helper rm_conffile /etc/init.d/udev-finish 226-1\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/init/udev-finish.conf 226-1\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/init/udev-fallback-graphics.conf 226-1\~ -- "$@"
-dpkg-maintscript-helper symlink_to_dir /usr/share/doc/udev libudev1 221-2\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/modprobe.d/fbdev-blacklist.conf 229-6\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/init/udev.conf 233-1\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/init/udevmonitor.conf 233-1\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/init/udevtrigger.conf 233-1\~ -- "$@"
-# End automatically added section
-# Automatically added by dh_installinit/11.1.6ubuntu1
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+# Automatically added by dh_installinit
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
 	if [ -x "/etc/init.d/udev" ]; then
-		update-rc.d udev defaults >/dev/null || exit 1
+		update-rc.d udev defaults >/dev/null || exit $?
 	fi
 fi
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/init.d/udev-mtab 204-1~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/udev/links.conf 204-9~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/init.d/udev-finish 226-1~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/init/udev-finish.conf 226-1~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/init/udev-fallback-graphics.conf 226-1~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper symlink_to_dir /usr/share/doc/udev libudev1 221-2~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/udev/rules.d/README 215-5ubuntu1~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/init.d/lvm2 228-2ubuntu2~ -- "$@"
 # End automatically added section
 
 
diff --git a/dpkg/info/unattended-upgrades.postinst b/dpkg/info/unattended-upgrades.postinst
--- a/dpkg/info/unattended-upgrades.postinst
+++ b/dpkg/info/unattended-upgrades.postinst
@@ -49,6 +49,8 @@ case "$1" in
 	NEWFILE="$CONFIG.ucftmp"
 	TEMPLATE="/usr/share/unattended-upgrades/50unattended-upgrades"
 	cp -a -f "$TEMPLATE" "$NEWFILE"
+	db_get unattended-upgrades/origins_pattern || true
+	sed -i 's/"origin=Debian,codename=${distro_codename},label=Debian-Security";/'"${RET}"'/' "$NEWFILE"
 	ucf --three-way --debconf-ok "$NEWFILE" "$CONFIG"
 	ucfr unattended-upgrades "$CONFIG"
 	rm -f "$NEWFILE"
@@ -59,19 +61,16 @@ case "$1" in
             && [ -f /etc/rc6.d/S[0-9][0-9]unattended-upgrades ] ; then
             update-rc.d -f unattended-upgrades remove
         fi
-        # Recover from broken dh_installinit override in versions < 0.93.1+nmu1 (or < 0.93.1ubuntu3 in Ubuntu)
-        if ([ "$(lsb_release -i -s)" != "Ubuntu" ] && dpkg --compare-versions "$2" lt "0.93.1+nmu1") || \
-               ([ "$(lsb_release -i -s)" = "Ubuntu" ] && dpkg --compare-versions "$2" lt "0.93.1ubuntu3"); then
+        # Recover from broken dh_installinit override in versions < 0.90ubuntu0.5
+        if dpkg --compare-versions "$2" lt "0.90ubuntu0.5"; then
             if [ -f /etc/rc0.d/K[0-9][0-9]unattended-upgrades ] \
             && [ -f /etc/rc6.d/K[0-9][0-9]unattended-upgrades ] ; then
             	update-rc.d -f unattended-upgrades remove
 	    fi
-	    # If running systemd, explicitely disable the service otherwise
-	    # the shutdown.target symlink will remain (See Debian Bug #797108)
-	    if [ -d /run/systemd/system ]; then
-	        if deb-systemd-helper --quiet was-enabled unattended-upgrades.service; then
-	            deb-systemd-helper disable unattended-upgrades.service >/dev/null || true
-	        fi
+	    # Explicitely disable the service otherwise the shutdown.target
+	    # symlink will remain (See Debian Bug #797108)
+	    if deb-systemd-helper --quiet was-enabled unattended-upgrades.service; then
+	        deb-systemd-helper disable unattended-upgrades.service >/dev/null || true
 	    fi
 	fi
     ;;
@@ -88,43 +87,43 @@ esac
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
 
-# Automatically added by dh_systemd_enable/11.1.6ubuntu2
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
-	# This will only remove masks created by d-s-h on package removal.
-	deb-systemd-helper unmask 'unattended-upgrades.service' >/dev/null || true
+# Automatically added by dh_systemd_enable
+# This will only remove masks created by d-s-h on package removal.
+deb-systemd-helper unmask unattended-upgrades.service >/dev/null || true
 
-	# was-enabled defaults to true, so new installations run enable.
-	if deb-systemd-helper --quiet was-enabled 'unattended-upgrades.service'; then
-		# Enables the unit on first installation, creates new
-		# symlinks on upgrades if the unit file has changed.
-		deb-systemd-helper enable 'unattended-upgrades.service' >/dev/null || true
-	else
-		# Update the statefile to add new symlinks (if any), which need to be
-		# cleaned up on purge. Also remove old symlinks.
-		deb-systemd-helper update-state 'unattended-upgrades.service' >/dev/null || true
-	fi
+# was-enabled defaults to true, so new installations run enable.
+if deb-systemd-helper --quiet was-enabled unattended-upgrades.service; then
+	# Enables the unit on first installation, creates new
+	# symlinks on upgrades if the unit file has changed.
+	deb-systemd-helper enable unattended-upgrades.service >/dev/null || true
+else
+	# Update the statefile to add new symlinks (if any), which need to be
+	# cleaned up on purge. Also remove old symlinks.
+	deb-systemd-helper update-state unattended-upgrades.service >/dev/null || true
 fi
 # End automatically added section
-# Automatically added by dh_installinit/11.1.6ubuntu2
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+# Automatically added by dh_installinit
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
 	if [ -x "/etc/init.d/unattended-upgrades" ]; then
-		update-rc.d unattended-upgrades defaults >/dev/null || exit 1
+		update-rc.d unattended-upgrades defaults >/dev/null
+	fi
+	if [ -x "/etc/init.d/unattended-upgrades" ] || [ -e "/etc/init/unattended-upgrades.conf" ]; then
+		invoke-rc.d unattended-upgrades start || exit $?
 	fi
 fi
 # End automatically added section
 
 
-# Explicitly enable and start the service. Debian Bug #797108 for 
+# Explicitely enable and start the service.i Debian Bug #797108 for 
 # deb-systemd-helper fails to correctly enable the unit. It checks for 
 # enablement using the content of the WantedBy= which has changed so it
 # sees the service as disable and will not enable it.
 case "$1" in
     configure)
-        if ( ([ "$(lsb_release -i -s)" != "Ubuntu" ] && dpkg --compare-versions "$2" lt "0.93.1+nmu1") || \
-                 ([ "$(lsb_release -i -s)" = "Ubuntu" ] && dpkg --compare-versions "$2" lt "0.93.1ubuntu3") )\
-	       && [ -d /run/systemd/system ]; then
-                # workaround systemd bug with enable --now which
-                # fails to start the unit
+        if dpkg --compare-versions "$2" lt "0.90ubuntu0.5" \
+	&& [ -d /run/systemd/system ]; then
+		# workaround systemd bug with enable --now which
+		# fails to start the unit
 		systemctl enable unattended-upgrades || true
 		systemctl start unattended-upgrades || true
 	fi
